FROM golang:1.25.1-alpine

# Install dependencies for Air
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Cache modules
COPY go.mod go.sum ./
RUN go mod download

# Copy everything (Air will rebuild when source changes)
COPY . .

# Default command runs Air (auto reload)
CMD ["air"]
