// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package repository

import (
	"context"
)

const createOrganisationMember = `-- name: CreateOrganisationMember :one
INSERT INTO organisation_members (user_id, organisation_id, role_id)
VALUES ($1, $2, $3)
RETURNING organisation_id, user_id, role_id, joined_at
`

type CreateOrganisationMemberParams struct {
	UserID         string `json:"user_id"`
	OrganisationID string `json:"organisation_id"`
	RoleID         string `json:"role_id"`
}

func (q *Queries) CreateOrganisationMember(ctx context.Context, arg CreateOrganisationMemberParams) (OrganisationMember, error) {
	row := q.db.QueryRow(ctx, createOrganisationMember, arg.UserID, arg.OrganisationID, arg.RoleID)
	var i OrganisationMember
	err := row.Scan(
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.JoinedAt,
	)
	return i, err
}

const getMemberByOrg = `-- name: GetMemberByOrg :one
SELECT organisation_id, user_id, role_id, joined_at FROM organisation_members
WHERE user_id = $1 AND organisation_id = $2
`

type GetMemberByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganisationID string `json:"organisation_id"`
}

func (q *Queries) GetMemberByOrg(ctx context.Context, arg GetMemberByOrgParams) (OrganisationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByOrg, arg.UserID, arg.OrganisationID)
	var i OrganisationMember
	err := row.Scan(
		&i.OrganisationID,
		&i.UserID,
		&i.RoleID,
		&i.JoinedAt,
	)
	return i, err
}

const isOrganisationOwner = `-- name: IsOrganisationOwner :one
SELECT EXISTS (
    SELECT 1
    FROM organisations
    WHERE id = $1 AND owner_id = $2
)
`

type IsOrganisationOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) IsOrganisationOwner(ctx context.Context, arg IsOrganisationOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrganisationOwner, arg.ID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const organisationMemberExists = `-- name: OrganisationMemberExists :one
SELECT EXISTS(
    SELECT 1
    FROM organisation_members
    WHERE organisation_id = $1
      AND user_id = $2
)
`

type OrganisationMemberExistsParams struct {
	OrganisationID string `json:"organisation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) OrganisationMemberExists(ctx context.Context, arg OrganisationMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, organisationMemberExists, arg.OrganisationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
