// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID              string             `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AnnouncmentText pgtype.Text        `json:"announcment_text"`
	OrganisationID  pgtype.Text        `json:"organisation_id"`
}

type ChatMember struct {
	ID            string             `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RoomID        string             `json:"room_id"`
	UserID        string             `json:"user_id"`
	LastMessageID pgtype.Text        `json:"last_message_id"`
}

type ChatMessage struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RoomID    string             `json:"room_id"`
	UserID    string             `json:"user_id"`
	Message   string             `json:"message"`
}

type ChatRoom struct {
	ID             string             `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganisationID pgtype.Text        `json:"organisation_id"`
	Name           pgtype.Text        `json:"name"`
}

type Kanban struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ProjectID string             `json:"project_id"`
	Name      string             `json:"name"`
	Status    interface{}        `json:"status"`
}

type KanbanCategory struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	KanbanID  string             `json:"kanban_id"`
	Name      pgtype.Text        `json:"name"`
}

type KanbanItem struct {
	ID               string             `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	KanbanCategoryID string             `json:"kanban_category_id"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Priority         interface{}        `json:"priority"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	EstimatedTime    pgtype.Int4        `json:"estimated_time"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
}

type LineDatum struct {
	ID           string             `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WhiteboardID string             `json:"whiteboard_id"`
	Stroke       pgtype.Text        `json:"stroke"`
	StrokeWidth  pgtype.Int4        `json:"stroke_width"`
	Tool         pgtype.Text        `json:"tool"`
	TextContent  pgtype.Text        `json:"text_content"`
}

type LinePoint struct {
	ID         int32   `json:"id"`
	Point      float64 `json:"point"`
	LineDataID string  `json:"line_data_id"`
}

type Organisation struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   pgtype.Text        `json:"description"`
	OwnerID       string             `json:"owner_id"`
	Website       pgtype.Text        `json:"website"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	Location      pgtype.Text        `json:"location"`
	Timezone      pgtype.Text        `json:"timezone"`
	IsActive      pgtype.Bool        `json:"is_active"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	Settings      []byte             `json:"settings"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DefaultRoleID pgtype.Text        `json:"default_role_id"`
}

type OrganisationMember struct {
	OrganisationID string             `json:"organisation_id"`
	UserID         string             `json:"user_id"`
	RoleID         string             `json:"role_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type Project struct {
	ID             string             `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Name           pgtype.Text        `json:"name"`
	OrganisationID string             `json:"organisation_id"`
	Status         interface{}        `json:"status"`
}

type ProjectMember struct {
	ID        int32       `json:"id"`
	ProjectID string      `json:"project_id"`
	UserID    string      `json:"user_id"`
	Role      interface{} `json:"role"`
}

type Role struct {
	ID             string      `json:"id"`
	OrganisationID pgtype.Text `json:"organisation_id"`
	Name           string      `json:"name"`
	BaseRoleID     pgtype.Text `json:"base_role_id"`
	Description    pgtype.Text `json:"description"`
}

type RolePermission struct {
	RoleID        string      `json:"role_id"`
	PermissionKey string      `json:"permission_key"`
	Allowed       pgtype.Bool `json:"allowed"`
}

type User struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Avatar    pgtype.Text        `json:"avatar"`
}

type WhiteboardRoom struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ProjectID pgtype.Text        `json:"project_id"`
	Name      pgtype.Text        `json:"name"`
}
