// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountOrganisations(ctx context.Context) (int64, error)
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrganisation(ctx context.Context, id string) error
	GetByEmail(ctx context.Context, email string) (User, error)
	GetOrganisationByID(ctx context.Context, id string) (Organisation, error)
	GetOrganisationBySlug(ctx context.Context, slug string) (Organisation, error)
	GetOrganisationsByOwner(ctx context.Context, arg GetOrganisationsByOwnerParams) ([]Organisation, error)
	GetUserOrganisations(ctx context.Context, arg GetUserOrganisationsParams) ([]Organisation, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	SearchOrganisations(ctx context.Context, arg SearchOrganisationsParams) ([]Organisation, error)
	UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error)
}

var _ Querier = (*Queries)(nil)
