// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password, username)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, deleted_at, username, email, password, avatar
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Avatar,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT
    id, created_at, updated_at, deleted_at, username, email, password, avatar
FROM users
WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Avatar,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, created_at, updated_at, deleted_at, username, email, password, avatar
FROM users
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Avatar,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id,
    username,
    avatar
FROM users
WHERE
    ($1 = '' OR username ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetUsersParams struct {
	Search interface{} `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type GetUsersRow struct {
	ID       string      `json:"id"`
	Username string      `json:"username"`
	Avatar   pgtype.Text `json:"avatar"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
